// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnV_44OlSOO8d0nDI671pV-rb7gheZuo',
    appId: '1:157983696558:web:be81df86e907b43f542f3f',
    messagingSenderId: '157983696558',
    projectId: 'registration-95775',
    authDomain: 'registration-95775.firebaseapp.com',
    storageBucket: 'registration-95775.firebasestorage.app',
    measurementId: 'G-ME4E0LD2ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTozCFt-KTWoRfoQmRffmFBP9jTyeBs5A',
    appId: '1:157983696558:android:94b629e0147e5348542f3f',
    messagingSenderId: '157983696558',
    projectId: 'registration-95775',
    storageBucket: 'registration-95775.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zan4Z_0CRbFLEqlY5tW0pHTzWflxkwU',
    appId: '1:157983696558:ios:c027881bddb001f8542f3f',
    messagingSenderId: '157983696558',
    projectId: 'registration-95775',
    storageBucket: 'registration-95775.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7zan4Z_0CRbFLEqlY5tW0pHTzWflxkwU',
    appId: '1:157983696558:ios:c027881bddb001f8542f3f',
    messagingSenderId: '157983696558',
    projectId: 'registration-95775',
    storageBucket: 'registration-95775.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTnV_44OlSOO8d0nDI671pV-rb7gheZuo',
    appId: '1:157983696558:web:ddc16f7cfbff4a79542f3f',
    messagingSenderId: '157983696558',
    projectId: 'registration-95775',
    authDomain: 'registration-95775.firebaseapp.com',
    storageBucket: 'registration-95775.firebasestorage.app',
    measurementId: 'G-RLQ9ZNG8L1',
  );
}
